UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Mocha Latte Medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced White Chocolate Mocha Large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced White Chocolate Mocha Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced White Chocolate Mocha';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Cherry Blossom Iced Latte Large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cherry Blossom Iced Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cherry Blossom Iced Latte';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Caramel bubbles Iced Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Caramel bubbles Iced Latte Large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Caramel bubbles Iced Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Coconut Iced Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Coconut Iced Latte Large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Coconut Iced Latte Medium';
UPDATE items SET price = 95.00 WHERE names->>'en' = 'Espresso';
UPDATE items SET price = 195.00 WHERE names->>'en' = 'Espresso Affogato';
UPDATE items SET price = 95.00 WHERE names->>'en' = 'Espresso Ristretto';
UPDATE items SET price = 120.00 WHERE names->>'en' = 'Espresso Macchiato';
UPDATE items SET price = 120.00 WHERE names->>'en' = 'Americano';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Americano Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Butter scotch Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Butter scotch Latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Piko Mocha';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Piko Mocha Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Pink Perry matcha latta';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Pink matcha latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cheese cake Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cheese cake Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Toffee Nut Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Toffee Nut Latte Medium';
UPDATE items SET price = 110.00 WHERE names->>'en' = 'Double Espresso';
