UPDATE items SET price = 350.00 WHERE names->>'en' = 'Oreo Crepe';
UPDATE items SET price = 300.00 WHERE names->>'en' = 'Pistachio Crepe';
UPDATE items SET price = 420.00 WHERE names->>'en' = 'Piko Crepe';
UPDATE items SET price = 320.00 WHERE names->>'en' = 'Cheesecake Crepe';
UPDATE items SET price = 300.00 WHERE names->>'en' = 'Chocolate Crepe';
UPDATE items SET price = 400.00 WHERE names->>'en' = 'Fruit Crepe';
UPDATE items SET price = 350.00 WHERE names->>'en' = 'Fettuccine Crepe';
UPDATE items SET price = 380.00 WHERE names->>'en' = 'Lotus Crepe';
UPDATE items SET price = 130.00 WHERE names->>'en' = 'Iced Americano';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Iced Americano large';
UPDATE items SET price = 150.00 WHERE names->>'en' = 'Iced Americano medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced butter scotch large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced butter scotch medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Iced butter scotch';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced piko latte';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced piko latte large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced piko latte medium';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Iced Pink Perry matcha latta';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Iced Pink Perry matcha latta learg';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Pink Perry matcha latta Medium';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Iced Pink matcha latte';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Iced Pink matcha latte large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Pink matcha latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced cheese cake latte';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Iced cheese cake latte large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced cheese cake latte medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Iced Toffee Nut Latte';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced Toffee Nut Latte Large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Toffee Nut Latte Medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced Zebra mocha latte large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Zebra mocha latte medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced Zebra mocha latte';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Iced Spanish Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced Spanish Latte medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Spanish Latte Large';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Iced Strawberry matcha latte';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Iced Strawberry matcha latte large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Strawberry matcha latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced strawberry mocha';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced strawberry mocha large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced strawberry mocha medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Iced Salted Caramel Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced salted caramel latte large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced Salted Caramel Latte medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced chai tea latte';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Iced chai tea latte Large';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced chai tea latte medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Iced Vanilla Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Iced Vanilla Latte Large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Iced Vanilla Latte Medium';
