UPDATE items SET price = 200.00 WHERE names->>'en' = 'Butter scotch Latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Piko Mocha';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Piko Mocha Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Pink Perry matcha latta';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Pink matcha latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cheese cake Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cheese cake Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Toffee Nut Latte';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Toffee Nut Latte Medium';
UPDATE items SET price = 110.00 WHERE names->>'en' = 'Double Espresso';
UPDATE items SET price = 120.00 WHERE names->>'en' = 'Ginger and lemon';
UPDATE items SET price = 120.00 WHERE names->>'en' = 'Flavoured tea';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Zebra Mocha';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Zebra Mocha Medium';
UPDATE items SET price = 120.00 WHERE names->>'en' = 'Lime blossom tea';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Spanish Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Spanish Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Strawberry matcha latte';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Strawberry Mocha Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Strawberry mocha latte Medium';
UPDATE items SET price = 150.00 WHERE names->>'en' = 'Sahlab with Cinnamon';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Salted Caramel Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Salted Caramel Latte Medium';
UPDATE items SET price = 40.00 WHERE names->>'en' = 'Tea';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Chai Tea Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Chai Tea Latte Medium';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Vanilla Latte';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Vanilla Latte Medium';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Flat White';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Flat White Medium';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Filter Coffee';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Filter Coffee with Milk';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Filter Coffee with Milk Medium';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Filter Coffee Medium';
UPDATE items SET price = 195.00 WHERE names->>'en' = 'V60';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'V60 Medium';
UPDATE items SET price = 95.00 WHERE names->>'en' = 'Turkish Coffee';
UPDATE items SET price = 135.00 WHERE names->>'en' = 'Double Turkish Coffee';
UPDATE items SET price = 95.00 WHERE names->>'en' = 'Cardamom Coffee';
UPDATE items SET price = 135.00 WHERE names->>'en' = 'Double cardamom Coffee';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Cappuccino';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Cappuccino Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Caramel Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Caramel Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Caramel Macchiato';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Caramel macchiato medium';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Cortado';
UPDATE items SET price = 140.00 WHERE names->>'en' = 'Latte';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Latte Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Matcha latte';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Mocha Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Mocha Latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hot Chocolate';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Hot Chocolate Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'White Mocha Latte';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'White Mocha Latte Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'White Hot Chocolate';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'White Hot Chocolate Medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Pineapple mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Pineapple mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Pineapple mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Passion orange mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Passion orange mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Passion orange mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Passion peach mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Passion peach mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Passion peach mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Orange peach mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Orange peach mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Orange peach mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Peach mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Peach mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Peach mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Pomegranate mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Pomegranate mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Pomegranate mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Ginger mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Ginger mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Ginger mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Strawberry mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Strawberry mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Strawberry mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Mojito classic RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Mojito classic 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Mojito classic soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Kiwi mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Kiwi mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Kiwi mojito soda medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Mango mojito RedBull medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Mango mojito 7up medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Mango mojito soda medium';
UPDATE items SET price = 290.00 WHERE names->>'en' = 'Mix berries mojito RedBull medium';
UPDATE items SET price = 260.00 WHERE names->>'en' = 'Mix berries mojito 7up medium';
UPDATE items SET price = 230.00 WHERE names->>'en' = 'Mix berries mojito soda medium';
UPDATE items SET price = 350.00 WHERE names->>'en' = 'Oreo Waffle';
UPDATE items SET price = 390.00 WHERE names->>'en' = 'Pistachio Waffle';
UPDATE items SET price = 280.00 WHERE names->>'en' = 'Chocolate Waffle';
UPDATE items SET price = 340.00 WHERE names->>'en' = 'Strawberry Waffle';
UPDATE items SET price = 450.00 WHERE names->>'en' = 'Fruit Waffle';
UPDATE items SET price = 450.00 WHERE names->>'en' = 'Lotus Waffle';
UPDATE items SET price = 300.00 WHERE names->>'en' = 'Marshmallow Waffle';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Opera cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Hazelnut Chimney Cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Chimney Cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Pistachio Cheesecake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Blueberry Cheesecake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Chocolate Cheesecake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Strawberry Cheesecake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Tiramisu';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Fondant chocolate';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Croissants';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Pistachio Cookies';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Hazelnut Cookies';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Raspberry Cookies';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Cookies';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Lotus Cookies';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Carrot Cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Honey Cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Brownie Cake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'San Sebastian Cake';
UPDATE items SET price = 320.00 WHERE names->>'en' = 'Oreo Pancake';
UPDATE items SET price = 350.00 WHERE names->>'en' = 'Pistachio Pancake';
UPDATE items SET price = 320.00 WHERE names->>'en' = 'Tiramisu Pancake';
UPDATE items SET price = 300.00 WHERE names->>'en' = 'Chocolate Pancake';
UPDATE items SET price = 450.00 WHERE names->>'en' = 'Fruit Pancake';
UPDATE items SET price = 400.00 WHERE names->>'en' = 'Lotus Pancake';
UPDATE items SET price = 350.00 WHERE names->>'en' = 'Mini Oreo Pancake';
UPDATE items SET price = 320.00 WHERE names->>'en' = 'Mini Pistachio Pancake';
UPDATE items SET price = 300.00 WHERE names->>'en' = 'Mini Chocolate Pancake';
UPDATE items SET price = 450.00 WHERE names->>'en' = 'Mini Fruit Pancake';
UPDATE items SET price = 360.00 WHERE names->>'en' = 'Mini Lotus Pancake';
UPDATE items SET price = 350.00 WHERE names->>'en' = 'Mixed Berry Pancake';
UPDATE items SET price = 0.00 WHERE names->>'en' = 'Pina colada';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Pineapple orange smoothie medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Pineapple smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Passion orange smoothie medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Passion mango smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Peach orange smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Passion peach smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Peach smoothie medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Strawberry smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Caribbean smoothie medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Minted lemonade medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Pink lemonade medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Strawberry lemonade smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Strawberry mango smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Mango smoothie medium';
UPDATE items SET price = 240.00 WHERE names->>'en' = 'Mix berries smoothie medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Orange juice';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Orange carrot';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Orange carrot medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Orange lemon';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Orange lemon medium';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Orange juice medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Apple juice';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Apple carrot';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Apple carrot medium';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Apple juice medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Carrot juice';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Carrot juice medium';
UPDATE items SET price = 170.00 WHERE names->>'en' = 'Lemonade';
UPDATE items SET price = 190.00 WHERE names->>'en' = 'Lemonade medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Pistachio frappucino Medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Vanilla frappucino Medium';
UPDATE items SET price = 210.00 WHERE names->>'en' = 'Ice cream Medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Caramel Frappucino Medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Cookies frappucino Medium';
UPDATE items SET price = 250.00 WHERE names->>'en' = 'Mocha Frappucino Medium';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Cool lime';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime apple bubbles';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cool lime apple bubbles Large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime apple bubbles Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime blueberry bubbles';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cool lime blueberry bubbles large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime blueberry bubbles Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime strawberry bubbles';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Cool lime strawberry bubbles Large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime strawberry bubbles Medium';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Cool lime strawberry mix';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime strawberry mix large';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime strawberry mix Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime large';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Cool lime mango mix';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Cool lime mango mix large';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime mango mix Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Cool lime Medium';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Hibiscus';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus apple bubbles';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Hibiscus apple bubbles large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus apple bubbles Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus blueberry bubbles';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Hibiscus blueberry mix';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus blueberry mix large';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus blueberry mix Medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Hibiscus blueberry bubbles large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus blueberry bubbles Medium';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus strawberry bubbles';
UPDATE items SET price = 160.00 WHERE names->>'en' = 'Hibiscus strawberry Mix';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus strawberry mix large';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus strawberry mix Medium';
UPDATE items SET price = 220.00 WHERE names->>'en' = 'Hibiscus strawberry bubbles large';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus strawberry bubbles Medium';
UPDATE items SET price = 200.00 WHERE names->>'en' = 'Hibiscus large';
UPDATE items SET price = 180.00 WHERE names->>'en' = 'Hibiscus Medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Oreo milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Chocolate milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Vanilla milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Strawberry milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Caramel milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Cookies milkshake medium';
UPDATE items SET price = 275.00 WHERE names->>'en' = 'Lotus milkshake medium';
